server:
  port: 3344
  
spring:  application:    name: cloud-config-center
  cloud:    config:      server:        git:          uri: https://github.com/Boom-fzy/project_config.git
          username: Boom-fzy
          password: fzy1234ys#
          search-paths:            - project_config
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  