server:
  port: 83
  
spring:  application:    name: nacos-order-consumer
  cloud:    nacos:      discovery:        server-addr: localhost:8848

service-URL: 
  service-payment-url: http://nacos-payment-provider